// -------------------- LOWEST PICES INTERFACE --------------------
export interface lowestPrices {
    productId: number,
    price: number,
    source: string,
    discount: number,
    asLowAsText: string
}

// -------------------- PRODUCT INFO INTERFACE --------------------
export interface productInfo {
    id: number,
    price: number,
    premium: number,
    yearReleased: string,
    sku: string,
    name: string,
    shortName: string,
    isActive: boolean,
    imagePath: string,
    mobileThumbnailUrl: string,
    currentStockInHand: number,
    currentPrimaryStock: number,
    currentSecondaryStock: number,
    currentTertiaryStock: number,
    allocatedAgainstInstock: number,
    allocatedAgainstTertiary: number,
    floor_Premium: number,
    ceiling_Premium: number,
    dgWareHouseStock: number,
    allocatedAgainstDGWarehouse: number,
    fourthWareHouseStock: number,
    allocatedAgainst4thWareHouse: number,
    fourthWareHouseShipmentDate: string,
    tertiaryExpectedShipmentDate: string,
    allocatedAgainstImpaired: number,
    askDollars1: number,
    askDollars2: number,
    askDollars3: number,
    askDollars4: number,
    askDollars5: number,
    tier1Min: number,
    tier1Max: number,
    tier2Min: number,
    tier2Max: number,
    tier3Min: number,
    tier3Max: number,
    tier4Min: number,
    tier4Max: number,
    tier5Min: number,
    tier5Max: number,
    metalId: number,
    ounces: number,
    metal: string,
    activeSalesEventId: number,
    productTypeId: number,
    productType: string,
    productTypeCode: string,
    discountType: string,
    qtyPlanned: number,
    qtySold: number,
    discount: number,
    salesEventName: null | string,
    salesExpiryDate: string,
    isPreSale: boolean,
    expiryDate: string,
    wholSalePremium: number,
    wholeSaleStock: number,
    allocateAgainstWholesale: number,
    wholeSaleUpdateTs: string,
    priceType: number,
    fixedPrice: number,
    backOrderDiscountDivisor: number,
    isGrouped: boolean,
    allocatedAgainstWholeSale4thWarehouseStock: number,
    allocatedAgainstWholeSaleTertiaryStock: number,
    wholeSale4thWarehouseStock: number,
    wholeSaleImapairedStock: number,
    allocatedAgainstWholeSaleImpairedStock: number,
    wholesaleFixedPriceDiscount: number,
    wholeSaleTertiaryStock: number,
    wholesaleTier1: number,
    isClearanceProduct: boolean,
    isProductSoldBefore: boolean,
    dummyInventoryReduction: number,
    tertiaryDummyInventoryReduction: number,
    productNameWithHypen: string,
    expectedShipmentDate: string,
    instockExpectedShipmentDateRange: string,
    isChild: boolean,
    salesTaxCode: string,
    taxStatus: string,
    backorderPlanQty: number,
    backorderSoldQty: number,
    availableTierCount: number,
    childs: any,
    isImpairedQty: number,
    impairedDiscount: number,
    asLowAs: lowestPrices[]
}

export interface menu {
    label: string;
    value: string
}