export interface avaTaxLinesDetailsInterface {
  id: 0;
  transactionLineId: 0;
  transactionId: 0;
  addressId: null;
  country: "US";
  region: "CA";
  countyFIPS: null;
  stateFIPS: null;
  exemptAmount: 0.0;
  exemptReasonId: null;
  inState: null;
  jurisCode: "06";
  jurisName: "CALIFORNIA";
  jurisdictionId: null;
  signatureCode: null;
  stateAssignedNo: "";
  jurisType: 1;
  jurisdictionType: 1;
  nonTaxableAmount: 0.0;
  nonTaxableRuleId: null;
  nonTaxableType: null;
  rate: 0.06;
  rateRuleId: null;
  rateSourceId: null;
  serCode: null;
  sourcing: null;
  tax: 0.0;
  taxableAmount: 0.0;
  taxType: "Sales";
  taxSubTypeId: "S";
  taxTypeGroupId: null;
  taxName: "CA STATE TAX";
  taxAuthorityTypeId: 45;
  taxRegionId: null;
  taxCalculated: 0.0;
  taxOverride: null;
  rateType: 71;
  rateTypeCode: "G";
  taxableUnits: 0.0;
  nonTaxableUnits: 0.0;
  exemptUnits: 0.0;
  unitOfBasis: "PerCurrencyUnit";
  isNonPassThru: false;
  isFee: false;
}
export interface avaTaxLinesInterface {
  id: 0;
  transactionId: 0;
  lineNumber: "1";
  boundaryOverrideId: null;
  customerUsageType: "";
  entityUseCode: "";
  description: "Standard Shipping";
  destinationAddressId: null;
  originAddressId: null;
  discountAmount: 0.0;
  discountTypeId: null;
  exemptAmount: 0.0;
  exemptCertId: 0;
  certificateId: null;
  exemptNo: "";
  isItemTaxable: false;
  isSSTP: null;
  itemCode: "STANDARD-SHIPPING";
  lineAmount: 0.0;
  quantity: 1.0;
  ref1: "";
  ref2: "";
  reportingDate: "2024-01-20T00:00:00";
  revAccount: null;
  sourcing: null;
  tax: 0.0;
  taxableAmount: 0.0;
  taxCalculated: 0.0;
  taxCode: "FR020100";
  taxCodeId: 4784;
  taxDate: "2024-01-20T00:00:00";
  taxEngine: null;
  taxOverrideType: null;
  businessIdentificationNo: null;
  taxOverrideAmount: null;
  taxOverrideReason: null;
  taxIncluded: false;
  details: avaTaxLinesDetailsInterface[];
  nonPassthroughDetails: [];
  lineLocationTypes: null;
  parameters: null;
  hsCode: "";
  costInsuranceFreight: 0.0;
  vatCode: "";
  vatNumberTypeId: 0;
}
export interface avaTaxAddressInterface {
  id: number;
  transactionId: number;
  boundaryLevel: number;
  line1: string;
  line2: string;
  line3: string;
  city: string;
  region: string;
  postalCode: string;
  country: string;
  taxRegionId: number;
  latitude: string;
  longitude: string;
}
export interface avaTaxSummaryinterface {
  country: string;
  region: string;
  jurisType: number;
  jurisCode: string;
  jurisName: string;
  taxAuthorityType: number;
  stateAssignedNo: string;
  taxType: string;
  taxSubType: string;
  taxName: string;
  taxGroup: string | null;
  rateType: number;
  rateTypeCode: string | null;
  taxable: number;
  rate: number;
  tax: number;
  taxCalculated: number;
  nonTaxable: number;
  exemption: number;
}
export interface avaTaxResponseInterface {
  id: number;
  code: string;
  companyId: number;
  date: string;
  paymentDate: string;
  status: number;
  type: number;
  batchCode: "";
  currencyCode: string;
  customerUsageType: "";
  entityUseCode: "";
  customerVendorCode: string;
  customerCode: string;
  exemptNo: string;
  reconciled: false;
  locationCode: string;
  reportingLocationCode: string;
  purchaseOrderNo: string;
  referenceCode: string;
  salespersonCode: string;
  taxOverrideType: string | null;
  taxOverrideAmount: string | null;
  taxOverrideReason: string | null;
  totalAmount: number;
  totalExempt: number;
  totalDiscount: number;
  totalTax: number;
  totalTaxable: number;
  totalTaxCalculated: number;
  adjustmentReason: number;
  adjustmentDescription: string | null;
  locked: false;
  region: string | null;
  country: string | null;
  version: number;
  softwareVersion: string | null;
  originAddressId: string | null;
  destinationAddressId: string | null;
  exchangeRateEffectiveDate: string;
  exchangeRate: number;
  isSellerImporterOfRecord: string | null;
  description: string | null;
  email: string | null;
  businessIdentificationNo: string | null;
  modifiedDate: string;
  modifiedUserId: number;
  taxDate: string;
  lines: avaTaxLinesInterface[];
  addresses: avaTaxAddressInterface[];
  locationTypes: string | null;
  summary: avaTaxSummaryinterface[];
  taxDetailsByTaxType: string | null;
  parameters: string | null;
  messages: string | null;
  invoiceMessages: string | null;
}
export interface avaTaxQueryProductsInterface {
  customerOrderProductId?: number;
  sku: string | null;
  productName: string | null;
  taxCode: string | null;
  quantity: number;
  price: number;
}
export interface avaTaxQueryInterface {
  line1: string;
  city: string;
  region: string;
  postalCode: string;
  country: string;
  customerCode: string;
  expeditedShippingCharges: number;
  standardShippingCharges: number;
  signatureConfirmationCharges: number;
  upgradeShipmentModeCharges: number;
  products: avaTaxQueryProductsInterface[];
}
